# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetWishListItems.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16GetWishListItems.proto\x12\x05proto\"+\n\x15\x43SGetWishListItemsReq\x12\x12\n\naccount_id\x18\x01 \x01(\x04\"5\n\x0cWishItemInfo\x12\x0f\n\x07item_id\x18\x01 \x01(\r\x12\x14\n\x0crelease_time\x18\x02 \x01(\x04\";\n\x15\x43SGetWishListItemsRes\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.proto.WishItemInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetWishListItems_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CSGETWISHLISTITEMSREQ']._serialized_start=33
  _globals['_CSGETWISHLISTITEMSREQ']._serialized_end=76
  _globals['_WISHITEMINFO']._serialized_start=78
  _globals['_WISHITEMINFO']._serialized_end=131
  _globals['_CSGETWISHLISTITEMSRES']._serialized_start=133
  _globals['_CSGETWISHLISTITEMSRES']._serialized_end=192
# @@protoc_insertion_point(module_scope)
